services:
  users:
    build:
      context: ../../
      target: dev
      dockerfile: ./microservices/users/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/microservices/users/src
      - ./test:/usr/src/app/microservices/users/test
      - ./@types:/usr/src/app/microservices/users/@types
      - ../../libs/ts:/usr/src/app/libs/ts
    depends_on:
      users-db:
        condition: service_healthy
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    ports:
      - 3002:5000

  users-db:
    build:
      context: ./database
    env_file:
      - ./database/.env
    volumes:
      - users-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  users-db-data:
