services:
  notifications:
    build:
      context: ../../
      dockerfile: ./microservices/notifications/Dockerfile
      target: dev
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/microservices/notifications/src
      - ./test:/usr/src/app/microservices/notifications/test
      - ./@types:/usr/src/app/microservices/notifications/@types
      - ../../libs/ts:/usr/src/app/libs/ts
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    depends_on:
      # schedules-ai:
      #   condition: service_healthy
      # schedules:
      #   condition: service_healthy
      notifications-db:
        condition: service_healthy
    ports:
      - 3001:5000

  notifications-db:
    build:
      context: ./database
    env_file:
      - ./database/.env
    volumes:
      - notifications-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  notifications-db-data:
